---
title: "Predict NBA2K Players' Rating based on Regular season stats"
author: "Steven Liu"
output:
    html_document:
        toc: TRUE
        toc_float: TRUE
---

## Introduction

NBA2K series is one of the most trending basketball games worldwide. Besides the game itself being fascinating, the NBA2K rating has also become the most objective and authorized measure of NBA players’ ability. This study aims to build a linear regression model to determine whether we can predict one’s newest NBA2K rating based on his current NBA season stats (per game), including minutes, points, rebounds, blocks, rebounds, assists, fouls, and turnover. Currently, the NBA2K ratings are manually assigned based on people’s impressions of players. By building such a model, we can obtain a statistically significant prediction to minimize bias while assigning the ratings. Besides, these predictions are useful for audiences to get a better understanding of players’ newest ability score; and as a reference in awards (e.g. MVP, MIP) selections. Some studies have shown that MVP winners are more likely to have more points per minute, points per game, and field goal percentage. As an extension, our model wishes to explore more pattern in data that reflects players’ overall ability.

## Download Report
[Download Report](https://github.com/Yuanxyyds/Data-Science-Projects/raw/main/NBA2K/nba2k-final-report.pdf)

 